baseurl: "/"
title: "thebugger.io testing blog"
page_load_js: "assets/js/main.js"
params:
  palette: yellow
  header:
    title: thebugger.io
    tagline: Blog created out of passion for Software Testing
    logo_img: "images/logo6.svg"
    logo_img_alt: Jakub Jaworski
    background_img: "images/mallorca.jpg"
    has_nav: true
    nav_links:
      - label: Home
        url: /
        style: link
      - label: About
        url: /about
        style: link
    has_social: true
    social_links:
      - label: GitHub
        url: https://github.com/JJaworski93
        style: icon
        icon_class: github
        new_window: true
      - label: LinkedIn
        url: https://www.linkedin.com/in/jakub-jaworski-060261162/
        style: icon
        icon_class: linkedin
        new_window: true
  footer:
    content: >-
      &copy; Jakub. All rights reserved. 
sass:
  input_file: sass/main.scss.njk
  output_file: assets/css/main.css
  indentWidth: 4
  outputStyle: nested
  precision: 10
templates:
  body_class: "palette-{{ site.params.palette }}"
